lib: [
  "_build/install/default/lib/tf/META" {"META"}
  "_build/install/default/lib/tf/opam" {"opam"}
  "_build/install/default/lib/tf/core/tf_core__Operation.cmi" {"core/tf_core__Operation.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Operation.cmx" {"core/tf_core__Operation.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Operation.cmt" {"core/tf_core__Operation.cmt"}
  "_build/install/default/lib/tf/core/tf_core__Operation.cmti" {"core/tf_core__Operation.cmti"}
  "_build/install/default/lib/tf/core/operation.mli" {"core/operation.mli"}
  "_build/install/default/lib/tf/core/tf_core__Protobuf.cmi" {"core/tf_core__Protobuf.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Protobuf.cmx" {"core/tf_core__Protobuf.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Protobuf.cmt" {"core/tf_core__Protobuf.cmt"}
  "_build/install/default/lib/tf/core/tf_core__Protobuf.cmti" {"core/tf_core__Protobuf.cmti"}
  "_build/install/default/lib/tf/core/protobuf.mli" {"core/protobuf.mli"}
  "_build/install/default/lib/tf/core/tf_core__Tensor.cmi" {"core/tf_core__Tensor.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Tensor.cmx" {"core/tf_core__Tensor.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Tensor.cmt" {"core/tf_core__Tensor.cmt"}
  "_build/install/default/lib/tf/core/tf_core__Tensor.cmti" {"core/tf_core__Tensor.cmti"}
  "_build/install/default/lib/tf/core/tensor.mli" {"core/tensor.mli"}
  "_build/install/default/lib/tf/core/tf_core__Tf_bindings.cmi" {"core/tf_core__Tf_bindings.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Tf_bindings.cmx" {"core/tf_core__Tf_bindings.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Tf_bindings.cmt" {"core/tf_core__Tf_bindings.cmt"}
  "_build/install/default/lib/tf/core/tf_bindings.ml" {"core/tf_bindings.ml"}
  "_build/install/default/lib/tf/core/tf_core.cmi" {"core/tf_core.cmi"}
  "_build/install/default/lib/tf/core/tf_core.cmx" {"core/tf_core.cmx"}
  "_build/install/default/lib/tf/core/tf_core.cmt" {"core/tf_core.cmt"}
  "_build/install/default/lib/tf/core/tf_core.ml-gen" {"core/tf_core.ml-gen"}
  "_build/install/default/lib/tf/core/tf_core__Tf_generated.cmi" {"core/tf_core__Tf_generated.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Tf_generated.cmx" {"core/tf_core__Tf_generated.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Tf_generated.cmt" {"core/tf_core__Tf_generated.cmt"}
  "_build/install/default/lib/tf/core/tf_generated.ml" {"core/tf_generated.ml"}
  "_build/install/default/lib/tf/core/tf_core__Wrapper.cmi" {"core/tf_core__Wrapper.cmi"}
  "_build/install/default/lib/tf/core/tf_core__Wrapper.cmx" {"core/tf_core__Wrapper.cmx"}
  "_build/install/default/lib/tf/core/tf_core__Wrapper.cmt" {"core/tf_core__Wrapper.cmt"}
  "_build/install/default/lib/tf/core/tf_core__Wrapper.cmti" {"core/tf_core__Wrapper.cmti"}
  "_build/install/default/lib/tf/core/wrapper.mli" {"core/wrapper.mli"}
  "_build/install/default/lib/tf/core/libtf_core_stubs.a" {"core/libtf_core_stubs.a"}
  "_build/install/default/lib/tf/core/tf_core.cmxa" {"core/tf_core.cmxa"}
  "_build/install/default/lib/tf/core/tf_core.a" {"core/tf_core.a"}
]
doc: [
  "_build/install/default/doc/tf/README.md"
  "_build/install/default/doc/tf/LICENSE"
]
